module.exports = (app,counterModule)=>
{
	app.get('/',(req,res)=>{
	    res.render('index');
	});
	app.get('/about',(req,res)=>
	{
		console.log('/about');
		res.render('about');
	});
	app.get('/visitCounter',(req,res)=>{
		counterModule.callCount((err,count)=>{
			if(err){
				console.log('[main.js][/visitCounter]err'+err);
				res.status(204);
			}else{
				res.send({visit:count});
			}
		});
	});
	app.get('/test',(req,res)=>{
	    res.render('editPage');
	});
}